### ISSUE TITLE
lib.scene fail to reload learned values after restart

### ISSUE THREAD

**Issue by kr2** [smarthomeNG/smarthome#282] opened 2018-09-19 13:05 UTC
for me the lib.scene failed to load the learned values after smarthomeng.py restart.
i think that line 170 in lib.scene.py should be removed. 
that worked for me.

**Comment by msinn** [comment] 2018-09-25 07:06
I cannot reproduce your problem.

Further I can't see why removing

```
 self._learned_values = {}
```
should fix the problem. It is the initial initialization in the load routine, to get an empty dict if no file with learned values can be found.

**Comment by kr2** [comment] 2018-09-25 11:06
_load_learned_values is called for every item with "scene" keyword. self._learned_values is a dict and should contain all learned values from all defined scenes. line 170 self._learned_values = {} clears the dict of the class at each iteration, when iterating over all items with "scene" keyword.

Maybe to clarify, I have more than one scene defined. I guess for only one, it could work fine.

**Comment by kr2** [comment] 2018-09-27 12:50
since i still got problems with the learned values, i did some more digging. below the somewhat better tested version of the fix.
changes:
- fixed learned values reset, in loading loop
- fixed saving values in _learned file that don't belong there (from different scene)
- enhancement _learned is only saved if necessary
- enhancement #283. the set_value keyword is optional and can be omitted. examples:
  * `{item: item.name, set_value: 'item.fade(dest=value, step=5, delta=.1)', value: 0.0, learn: false}`
  * `{item: item.name, set_value: 'item(value); item.timer(3, 0, auto=False)', value: 100.0, learn: true}`
  * ...

[scene.zip](https://github.com/smarthomeNG/smarthome/files/2424064/scene.zip)

**Comment by msinn** [comment] 2020-12-24 08:11
This issue is fixed by two bugixes that are in the develop branch and will to into release v1.8

**Comment by msinn** [comment] 2021-02-08 13:52
v1.8 fixed it

**Closed by msinn** 2021-02-08 13:52 UTC
Labels: core, resolved
