### ISSUE TITLE
knx plugin working differently than written in readme

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#244] opened 2017-11-27 10:41 UTC
I've just figured out that knx_poll expects a number and an additional knx_listen attribute.
It states differently in the readme file:
https://github.com/smarthomeNG/plugins/tree/master/knx

Wouldn't knx_reply be more appropriate in this context than knx_listen?

**Comment by onkelandy** [comment] 2017-11-27 21:55
I can't figure out how I can read a KNX value based on a trigger... I'd love to poll a GA when some item has a specific value. But it looks like the reading only works when setting a time value :( Am I doing something wrong? Would be perfect to make a manual poll possible.

**Comment by smaiLee** [comment] 2017-11-28 09:47
This may work:
You could call [sh.knx.groupdread](https://github.com/smarthomeNG/plugins/tree/master/knx#groupreadga-cachefalse) in a logic to trigger the reading and use just knx_listen instead of knx_poll in the target item.
The logic itself can be triggered by by knx_listen to another GAD in logic.conf

**Comment by onkelandy** [comment] 2017-11-28 10:29
Thanks for the hint, works perfectly fine with the logic.
Anyhow, the knx_poll function itself right now doesn't work the way it's documented. I don't dare to touch such an important plugin myself ;)

**Comment by smaiLee** [comment] 2017-11-28 10:44
This seems to be fixed already in develop branch: smarthomeNG/plugins@57c8426446e44ead37d9b58f67b7354c493ae27c
But your right, the public documentation should reflect master and not develop.

**Comment by Foxi352** [comment] 2017-11-28 10:49
I wrote the knx_poll function and did so in develop branch. At the beginning the function only allowed a time to be set and used the knx_listen GA. After discussions we agreed that it would be better to allow the GA to be explicitly set as argument in knx_poll as it may differ from the GA in knx_listen.

But i was not aware, until know, that someone ported knx_poll back to the master branch. It was not me, and the one who did it probably did so between my first commit and my fix later on.

I see two options: Change the readme in master or merge the "fix" from develop back into master.

**Comment by onkelandy** [comment] 2017-11-28 11:29
I'd prefer a Hotfix 3 for the master branch ;)
Will it be possible to poll the GA on updating a "helper item" that only has knx_poll without an interval defined?

**Comment by onkelandy** [comment] 2017-12-05 23:19
Any decision yet?
@Foxi352 as you are updating the knx plugin.. what do you think about this..:
https://github.com/smarthomeNG/smarthome/issues/88

**Comment by Foxi352** [comment] 2017-12-11 18:44
@onkelandy Will try to look into both issue the next days. I'm a bit busy atm due to end of year deadlines @ work.

**Comment by smaiLee** [comment] 2017-12-12 12:14
There seems to be another issue with knx_poll:
If I read the code right, knx_poll can not be combined with knx_send or knx_status.
On [line 477](https://github.com/smarthomeNG/plugins/blob/00f151b23aea74ea299134c5e19b7a074cc54a58/knx/__init__.py#L477) is a return statement, so the knx_poll part is not reached.

**Comment by msinn** [comment] 2018-05-05 18:41
@Foxi352 Any news on this issue?

**Comment by Foxi352** [comment] 2018-05-13 09:29
@smaiLee 

> If I read the code right, knx_poll can not be combined with knx_send or knx_status.

Yes you are right, and i don't see why one should exclude the other. I moved the item return if below knx_poll for testing. Will be in the next push after i did some tests locally.

**Comment by Foxi352** [comment] 2018-05-13 09:35
I will push the changes and updates into develop today.

But how should i backport the knx_poll to have expected behaviour as described in readme ? Update master ? Update 1.4.2b tag ?

**Comment by Foxi352** [comment] 2018-05-13 13:55
> If I read the code right, knx_poll can not be combined with knx_send or knx_status.

Should be fixed by https://github.com/smarthomeNG/plugins/commit/303030feeeec73c4d814cde4e4d71e7c460579f2

**Comment by msinn** [comment] 2018-05-14 16:40
@Foxi352 
> But how should i backport the knx_poll to have expected behaviour as described in readme ? Update master ? Update 1.4.2b tag ?

Just wait for the next Release. End of June should be a time target (when we mee the Most wanted  Release Interval).

**Comment by bmxp** [comment] 2018-07-14 13:18
Can we close this issue now since the master 1.5 is gone live?

**Comment by Foxi352** [comment] 2018-07-14 14:13
+1 from me

**Closed** 2018-07-14 15:07 UTC
Labels: bug
