### ISSUE TITLE
admin interface: Warning after changing plugin loglevel

### ISSUE THREAD

**Issue by aschwith** [smarthomeNG/smarthome#522] opened 2023-01-24 17:19 UTC
Changing a plugin loglevel via the admin interface -> logs -> logger list sucessfully changes the according log level but triggers a warning: 

WARNING  modules.admin.api_loggers REST_dispatch_execute: plugins.xyz: 'LoggersController' object has no attribute 'create_backupfile'

**Comment by wvhn** [comment] 2023-01-24 17:24
the same happens after a change in modules logger.

**Comment by msinn** [comment] 2023-02-05 13:55
@aschwith Do you have more details? I cannot reproduce it (running the develop branch)
@onkelandy I can't reproduce that either.

Changeing a logger's level, I get the following log entries, but no WARNING:
```
2023-02-05  14:53:36 NOTICE   modules.admin.api_loggers set_active_logger_level(): logger=lib.module, level=INFO
2023-02-05  14:53:36 NOTICE   modules.admin.api_loggers set_active_logger_level(): lg=<Logger lib.module (NOTICE)>, lglevel=20
2023-02-05  14:53:36 NOTICE   modules.admin.api_loggers load_logging_config: shng_version=x
2023-02-05  14:53:36 NOTICE   modules.admin.api_loggers  - old level=NOTICE
```

**Comment by onkelandy** [comment] 2023-02-05 15:15
Think you wanted to mention @wvhn ..?
I don't have any issues when changing the log level with most recent develop branch.

**Comment by wvhn** [comment] 2023-02-05 18:19
I noticed the issue on master branch. Haven't tested yet on develop.

**Comment by aschwith** [comment] 2023-02-05 18:46
Same for me: Issue occurs in Master v1.9.3. Did not doublecheck current develop version.

**Comment by msinn** [comment] 2023-03-09 10:41
I couldn't find it at first, because it only happens if the etc/logging.yaml hasn't been changed by the admin interface before. In this case SmartHomeNG tries to create a backup file before writing the new configuration to disk.

Since the error occurred for you, the new configuration wasn't written to disk.

It will be fixed in the next release.

**Comment by msinn** [comment] 2023-03-14 12:55
SmartHomeNG v1.9.4 has been released

**Closed by msinn** 2023-03-14 12:55 UTC
Labels: resolved

**Comment by aschwith** [comment] 2023-03-14 19:04
Issue no longer occurs under v1.9.4. Thanks for fixing.
