### ISSUE TITLE
Make all plugins a SmartPlugin

### ISSUE THREAD

**Issue by ohinckel** [smarthomeNG/smarthome#230] opened 2017-09-03 21:40 UTC
I just started to rewrite some plugins to make it a `SmartPlugin` - see https://github.com/smarthomeNG/plugins/pull/69.

Maybe I'll migrate others too, maybe I'll not. To have an overview about what is still open to migrate here's list (found out using `grep -L SmartPlugin plugins/*/__init__.py`):
*  [ ] boxcar/__init__.py  ->  marked **deprecated** -> moved to **archive**
* [x] dmx/__init__.py
* [x] easymeter/__init__.py  ->  marked **deprecated**
* [x] ebus/__init__.py
* [ ] ecmd/__init__.py  ->  marked **deprecated**
* [ ] elro/__init__.py  ->  marked **deprecated**
* [x] homematic/__init__.py  (msinn: complete rewrite planned after the shNG v1.4 release)
* [x] hue/__init__.py
* [ ] iaqstick/__init__.py  ->  marked **deprecated**
* [x] kathrein/__init__.py
* [x] kodi/__init__.py (formerly known as xbmc) - https://github.com/smarthomeNG/plugins/pull/95
* [x] milight/__init__.py
* [x] mpd/__init__.py -> https://github.com/smarthomeNG/plugins/pull/98
* [x] mqtt/__init__.py -> mqtt_1_0 is deprecated and should be moved into `deprecated_plugins` folder
* [ ] netio230b/__init__.py  ->  marked **deprecated** -> moved to **archive**
* [ ] nma/__init__.py  ->  marked **deprecated** --> moved to **archive**
* [x] onewire/__init__.py -> @Foxi352 
* [ ] openenergymonitor/__init__.py -> Plugin is probably dead, because the used service changed their business model -> moved to **archive**
* [x] raumfeld/__init__.py
* [x] roomba/__init__.py
* [x] rrd/__init__.py (should probably be retired instead of being made s spartplugin. rrd is quite dead)
* [x] russound/__init__.py
* [ ] smawb/__init__.py  ->  marked **deprecated** --> moved to **archive**
* [ ] snom/__init__.py  ->  marked **deprecated**
* [x] solarlog/__init__.py
* [x] speech/__init__.py
* [ ] tellstick/__init__.py  ->  marked **deprecated** --> moved to **archive**
* [x] volkszaehler/__init__.py
* [ ] vr100/__init__.py  ->  marked **deprecated**
* [x] xmpp/__init__.py

The migration should include the following steps:
* move global initialization `logger = logging.getLogger(...)` to `__init__()` method: `logging = logging.getLogger(__name__)` and replace all usage from `logger.` to `self.logger.`
* import SmartPlugin: `from lib.model.smartplugin import SmartPlugin` - should be after the system import
* inherit main plugin class from `SmartPlugin` and add the following two constants:
```
ALLOW_MULTIINSTANCE = True
PLUGIN_VERSION = '1.3.0'
```
* check `README.md` file to additionaly include a `.yaml` configuration example for plugin and items
* check `README.md` to include an updated license header

For my migrations I used the `database` plugin as reference (for position of `import` statement, for license header, for maintainer/author line, for README.md changes see [dev plugin](https://raw.githubusercontent.com/smarthomeNG/smarthome/master/dev/sample_plugin/README.md)).

**Comment by msinn** [comment] 2017-09-03 22:04
mqtt_1_0 is deprecated and need not to be converted.

For the migration it is worthwhile to take a look at the sample plugin under /dev/sample_plugin.

**Comment by onkelandy** [comment] 2017-09-03 22:10
xbmc is interesting for me personally.. I might have a look at that, rename it to kodi and pump it up with more features as it is very rudimentary at the moment. But I'll finish the avdevice plugin first... and the image.. still in progress ;)

**Comment by bmxp** [comment] 2017-09-05 11:14
I think you should either declare ``ALLOW_MULTIINSTANCE = False`` or update the conf query to has_iattr(conf, ...) instead of just conf(...)

**Comment by ssudholt** [comment] 2017-09-18 05:53
@onkelandy I did some fiddeling with the XBMC plugin already and would be happy to provide it. If desired, I could open up a PR with the current stuff I have which could then be used for additional feature requests.

**Comment by onkelandy** [comment] 2017-09-18 06:26
@ssudholt would be perfect! Let me know please as soon as it is in the new develop. Maybe you can also post the code in the forum to make testing easier and faster?
https://knx-user-forum.de/forum/supportforen/smarthome-py/25900-xbmc-plugin

**Comment by msinn** [comment] 2017-09-19 20:51
When converting a classic plugin to a smartPlugin please update the plugin.yaml metadata file in the plugin's directory.

**Comment by Foxi352** [comment] 2017-09-27 15:57
I am currently working on the onewire. Already converted to smartplugin but i want to fill in plugin.yaml before merging.

**Comment by Foxi352** [comment] 2017-09-27 16:02
Wird eigentlich das folgende in der init.py noch gebraucht, oder kommt das jetzt aus der plugin.yaml ?

    ALLOW_MULTIINSTANCE = False
    PLUGIN_VERSION = '1.3.1'

**Comment by psilo909** [comment] 2017-09-27 16:21
@Foxi352 aktuell schon noch, das backend wertet das noch aus. und das MI attribut müsste auch in der multiinstanzlogik noch eine bedeutung haben
@msinn wir müssen hier aber tunlichst mal eine entscheidung treffen und ggf alles umstellen... ich bin auch kein freund diese infos redundant zu haben

**Comment by Foxi352** [comment] 2017-09-27 16:59
@psilo909 Also ich müsste mich gewaltig irren, aber es sieht so aus als ob er Multiinstance aus dem Plugin nimmt aber die Version aus dem yaml ? Version war im Backend leer bis ich es in's yaml schrieb ...

**Comment by psilo909** [comment] 2017-09-27 17:03
@Foxi352 in der pluginübersicht ist im DEV backend schon das aus yaml ja.

aber noch nicht in der systemübersicht und dem PIP check

**Comment by psilo909** [comment] 2017-09-27 17:04
mindestens die version sollte raus.. ich baue das backend nächste woche mal komplett auf yaml um und schaue mir mal an, wie das MI attribut ausgewertet wird.

**Comment by ohinckel** [comment] 2017-09-27 17:51
@psilo909 vielleicht moechtest du zum Thema MI auch nochmal einen Blick in den folgenden PR https://github.com/smarthomeNG/smarthome/pull/127 werfen. Dort hatte ich auch ueber das Konfigurieren von MI in der Plugin-Konfiguration diskutiert (fuehlt sich fuer mich immer noch nicht rund an - section name vs. instance value).

**Comment by psilo909** [comment] 2017-09-27 17:59
@Foxi352 http://smarthomeng.de/dev/development_plugin/plugin_metadata.html

**Comment by psilo909** [comment] 2017-09-27 17:59
: | After  the completion of the implementation of metadata for plugins, the  following variables in the Python code of SmartPlugins need not be set  anymore. They are read from the global metadata and are automatically  set in the instance of the plugin:  ALLOW_MULTIINSTANCE PLUGIN_VERSION  The variable PLUGIN_VERSION should be set (even if it is  not needed). If it is set, the version numbers defined in __init__.py  and plugin.yaml are compared to ensure they match. If they don’t match,  an error is logged and the plugin is not loaded.
-- | --

**Comment by psilo909** [comment] 2017-09-27 18:01
@ohinckel der umbau lag aktuell bei @msinn, man sollte aber ggf nochmal gemeinsam drüber sprechen. womöglich sogar -schauder- in einer kurzen telko

**Comment by psilo909** [comment] 2017-09-27 18:01
der mumble server von @encbladexp ist noch oben ;)

**Comment by Foxi352** [comment] 2017-09-27 18:49
@psilo909 Ok, also MI aus der init raus und nur in der yaml. VERSION in beiden ... Das mit den Version in beiden wird dann wohl auch so bleiben zweck Kontrolle....

Richtig ? Hab die Änderungen die ich bis jetzt on onewire gemacht habe schon gepushed. Kannst dir ja mal das plugin.yaml ansehen.

**Comment by onkelandy** [comment] 2017-11-05 10:57
@ssudholt any news on xbmc plugin?

**Comment by ssudholt** [comment] 2017-11-07 20:43
@onkelandy sry, I didn't have much time lately. I just finished up a first version of the [Kodi plugin](https://github.com/smarthomeNG/plugins/pull/95). If you got time, I'd be glad if you could do some testing. I'm currently running some tests as well. Looks like everything is working so far.

If there are more feature requests for the plugin, I can add them. Otherwise I'll squash the commits and request a merge.

**Comment by msinn** [comment] 2017-12-01 12:18
After the release of snNG I am going to do a full rewrite of the homematic plugin. For the moment I have only fixed that it polls homematic information not only once on start.

**Comment by bmxp** [comment] 2018-07-14 13:39
It seems as if not much happened here except for four plugins. Is there still some interest in making all Plugins a smartplugin?

**Comment by bmxp** [comment] 2018-12-03 16:05
Ok, @msinn initiated three questionaires at KNX User Forum
1. [Part 1](https://knx-user-forum.de/forum/supportforen/smarthome-py/1260102-umfrage-welche-classic-plugins-werden-genutzt-teil-1)
2. [Part 2](https://knx-user-forum.de/forum/supportforen/smarthome-py/1260103-umfrage-welche-classic-plugins-werden-genutzt-teil-2)
3. [Part 3](https://knx-user-forum.de/forum/supportforen/smarthome-py/1260104-umfrage-welche-classic-plugins-werden-genutzt-teil-3)

The results as of start of december ordered by votes are:

* [7] volkszaehler
* [5] dmx
* [5] easymeter
* [5] milight
* [3] roomba
* [3] solarlog
* [3] speech
* [2] kathrein
* [2] nma
* [2] raumfeld
* [1] ecmd
* [1] elro
* [1] iaqstick
* [1] rrd
* [1] russound
* [1] snom
* [1] vr100

No votes:
* [0] boxcar
* [0] netio230b
* [0] smawb
* [0] tellstick
* [0] openenergymonitor

I would like to exclude the plugins with no votes from next release. But how should we handle those with votes > 1? We might make them a smart Plugin but likely have to way to test with hardware they support.
The plugins having only one vote should probably excluded, too as only one person uses them. We do not have the manpower to update all of them...

**Comment by msinn** [comment] 2019-03-17 11:17
Instead of excluding the classic plugins with no votes from release 1.6, I  marked them as deprecated.

In plugin.yaml:
```
plugin:
    ...
    state: deprecated
```
If someone uses the plugin(s), he gets a WARNING in the log file. 
Those plugins should then be excluded from release 1.7.

We could mark the plugins with one vote as deprecated too.

**Comment by bmxp** [comment] 2019-03-17 11:46
Funny, just before your post I was working on a comment how to proceed here. I think this is a good solution and we may close this issue if @ohinckel agrees.

**Comment by ohinckel** [comment] 2019-03-17 19:39
Is the deprecation also shown in the backend too? I think just logging a warning into the log file could be overseen by the users. Showing a warning in the backend UI would is more noticable.

Of course, plugins not in use anymore could be deprecated and I think, most of them we do not know the (original) author. Further nobody want (or is able) to migrated them and test them.

So, it's OK to deprecate them. But still there's a list of plugins having votes and are classic plugins. Should we migrate them or do we want to support them in the future too?

**Comment by msinn** [comment] 2019-03-18 11:38
I liked the idea and implemented a warning icon and description in the admin gui. I think we shouldn't bother adding it to the backend plugin (since it will be deprecated not too far from now)

I think we should try to migrate classic plugins with more than one vote. Maybe the intrest in converting/testing gets bigger with v1.6. The admin gui is able to configure the plugins, but not classic plugins.

**Comment by bmxp** [comment] 2019-05-01 10:56
The following Plugins are not SmartPlugins as of May 1st, 2019

* [5] dmx
* [5] easymeter
* [5] milight
* [3] roomba
* [3] solarlog
* [3] speech
* [2] kathrein
* [2] nma
* [2] raumfeld
* [1] ecmd
* [1] elro
* [1] iaqstick
* [1] rrd
* [1] russound
* [1] snom
* [1] vr100

No votes are questionnaire in knxuf so marked as deprecated for 1.6 and will be removed for SHNG 1.7
* [ ] boxcar, no votes --> deprecated
* [ ] netio230b, no votes --> deprecated
* [ ] openenergymonitor, no votes --> deprecated
* [ ] smawb, no votes --> deprecated
* [ ] tellstick, no votes --> deprecated

Waiting for PR from @ssudholt 
* [ ] xbmc

**Comment by bmxp** [comment] 2019-12-21 15:56
Update December 21st 2019

The following Plugins are still not SmartPlugins:

* [7] dmx
* [5] milight
* [3] roomba
* [3] solarlog
* [3] speech
* [2] kathrein
* [2] nma
* [2] raumfeld
* [1] ecmd
* [1] elro
* [1] iaqstick
* [1] rrd
* [1] russound
* [1] snom
* [1] vr100

IMHO deprecated since there is the DLMS plugin
* [5] easymeter --> queries a dlms based smartmeter with fixed params.

No votes are questionnaire in knxuf so marked as deprecated for 1.6 and will be removed for SHNG 1.7
* [ ] boxcar, no votes --> deprecated
* [ ] netio230b, no votes --> deprecated
* [ ] openenergymonitor, no votes --> deprecated
* [ ] smawb, no votes --> deprecated
* [ ] tellstick, no votes --> deprecated
* [ ] xbmc --> deprecated
  (Was waiting for PR from @ssudholt which never came. Onkelandy wrote kodi which is new name for xbmc)

**Comment by bmxp** [comment] 2019-12-23 07:18
dmx is now a SmartPlugin (in develop)

**Comment by bmxp** [comment] 2019-12-24 13:12
and so is milight plugin

**Comment by bmxp** [comment] 2020-01-28 20:08
I think we should mark the above plugins as deprecated and move them to an archive for the next release. Then we should close this issue here.

**Comment by psilo909** [comment] 2020-01-29 06:33
I agree

**Comment by msinn** [comment] 2020-03-02 08:32
I marked the plugins above that have not been converted to SmartPlugin deprecated

**Comment by msinn** [comment] 2020-06-26 09:51
At the moment the following plugins are not a SmartPlugin:
```
plugin_metadata_checker.py v1.7.3 - Checks the care status of plugin metadata

                                Plugi         Plugin  Item       Plugin  Plugin 
Plugin         Version  State   Type  Info    Params  Attrib.    Funct.  Logics 
-------------- -------- ------- ----- ------- ------- ---------- ------- -------
asterisk       1.3.0    ready   Class Ok      -       -          -       -      
cli            1.4.2    qa-pass Class Ok      -       -          -       -      
easymeter      -        depreca Class Ok      -       -          -       -      
ecmd           -        depreca Class Ok      -       -          -       -      
elro           -        depreca Class Ok      -       -          -       -      
iaqstick       -        depreca Class Ok      -       -          -       -      
lirc           1.4.1    ready   Class Ok      -       -          -       -      
mpd            1.4.1    ready   Class Ok      -       -          -       -      
operationlog   1.3.0    ready   Class Ok      -       -          -       -      
raumfeld       -        ready   Class Ok      -       -          -       -      
snom           -        depreca Class Ok      -       -          -       -      
vr100          -        depreca Class Ok      -       -          -       -      

13 plugins of 149 plugins total

```
Some are already marked as deprecated.

**Comment by onkelandy** [comment] 2020-12-06 19:09
So raumfeld is the only one remaining? There is a raumfeld_ng plugin from @greentux - does this replace the old raumfeld so that can be set deprecated? Is the new raumfeld_ng ready or still in develop state?

**Comment by bmxp** [comment] 2020-12-07 16:28
raumfeld seems to be abondoned. raumfeld_ng works as @greentux states. So we can declare the old raumfeld plugin as deprecated as well.

**Comment by greentux** [comment] 2020-12-09 13:01
Confirmed. raumfeld had only initial features.

**Comment by bmxp** [comment] 2020-12-12 07:50
I would suggest to close this thread now since all important plugins are converted and the rest ist marked as deprecated.
@msinn any objections?

**Comment by msinn** [comment] 2020-12-13 12:35
No objections from my side

**Closed by msinn** 2020-12-13 12:35 UTC
Labels: plugins
