### ISSUE TITLE
Backend Items

### ISSUE THREAD

**Issue by awgithubaw** [smarthomeNG/smarthome#134] opened 2016-10-15 14:18 UTC
If using knx_send or knx_init following way:

knx_send = 1/4/110 | 1/4/111 | 1/4/112 | 1/4/113

tree structure is lost from this point on. Could be depend of problem with building item tree in SmarthomeNG.

**Comment by bmxp** [comment] 2016-10-16 06:43
Hm. Seems as if in **plugins/backend/templates/items.html** around line 91 there needs to be a deeper check of **config[key]**. Maybe @psilo909 can fix this.

**Comment by psilo909** [comment] 2016-10-16 08:43
i dont get it, with recent version of DEV i can add this line to my item:
![tert](https://cloud.githubusercontent.com/assets/15831643/19416290/6a5fd372-938d-11e6-89de-7f434ba3155c.PNG)

**Comment by psilo909** [comment] 2016-10-16 08:47
Full information:
![fdghdfg](https://cloud.githubusercontent.com/assets/15831643/19416310/f77ee39c-938d-11e6-82ab-3e8f2ca79a23.PNG)
![jghj](https://cloud.githubusercontent.com/assets/15831643/19416311/f9a8d218-938d-11e6-865b-8f2e40c372c7.PNG)

**Comment by bmxp** [comment] 2016-10-16 16:30
I just checked it with 1.2.448 and it seems to be working as intended. @awgithubaw can you please provide more info on your used version?

**Comment by awgithubaw** [comment] 2016-10-27 12:05
Probably it's working and the "problem" is that with knx_send and knx_listen you can combine more than one group adress which I tried to combine with knx_init (also with more than one GA). In this point the documetnation is not that clear, which attribut can bu used with combined GAs and which not.

**Comment by psilo909** [comment] 2016-10-27 15:06
@awgithubaw does it work with knx_send at your place? you wrote it is not working with init and send..

**Comment by bmxp** [comment] 2016-10-28 05:10
@awgithubaw Maybe you can improve https://github.com/smarthomeNG/smarthome/blob/master/plugins/knx/README.md with the just aquired knowledge to clarify when multiple GA can be used?

**Comment by bmxp** [comment] 2016-10-28 05:11
@awgithubaw Maybe you could also give a feedback if it now works (with latest develop) and wether this issue can be closed?

**Comment by psilo909** [comment] 2016-10-31 06:21
@awgithubaw i also request feedback on that issue.

**Comment by psilo909** [comment] 2016-11-02 17:18
@awgithubaw hello?

**Comment by awgithubaw** [comment] 2016-11-02 20:28
Sorry, have no info received from github (is there a possibility to send mails with new comments?). I tested some more by now. It's normal working except when you use it with knx_init like

knx_init = 1/4/110 | 1/4/111 | 1/4/112 | 1/4/113

knx_send and knx_listen work this way.

How I've learned, with knx_init you may not use this, so the backend works like it should. I'll update the wiki tomorrow (hopefully) to clarify it.

But I couldn't test with latest develop, because I'm still on master branch and still don't realizen how to use different states in parallel.

**Comment by psilo909** [comment] 2016-11-03 04:55
@awgithubaw so we can close the issue?

**Comment by awgithubaw** [comment] 2016-11-03 06:07
Yes, it can be closed - thank you!

**Closed** 2016-11-03 09:24 UTC
