### ISSUE TITLE
Bug Crontab weekday does not work with range

### ISSUE THREAD

**Issue by int-red** [smarthomeNG/smarthome#307] opened 2019-01-14 10:59 UTC
When specifing a range for weekday like 0-4 which would be Monday to Friday the crontab does not work. Next execution time is given as 2029

When I use a list instead: 0,1,2,3,4 the crontab works.

Also evaluation of weekday is not compatible to Linux syntax.
Linux:
0 - Sun      Sunday
1 - Mon      Monday
2 - Tue      Tuesday
3 - Wed      Wednesday
4 - Thu      Thursday
5 - Fri      Friday
6 - Sat      Saturday
7 - Sun      Sunday

SmarthomeNG:
0=Monday  6=Sunday

**Comment by smaiLee** [comment] 2019-01-17 20:29
> When specifing a range for weekday like 0-4 which would be Monday to Friday

Additional information: In smarthome.log it reads
> ERROR    lib.scheduler    Error parsing crontab "0 19 * 0-4": invalid literal for int() with base 10: '0-4'

**Comment by msinn** [comment] 2019-03-10 16:54
I think it is not a bug. It is a feature request.

smarthome.py and SmartHomeNG have not support for a range of weekdays. A coma seperated list should work:

> wday: weekday, single value from 0 to 6 (0 = Monday), or comma separated list, or * (every day)

Documentatiion says it: 0 = Monday (Linux compatibility was not intended by the original author)

**Comment by int-red** [comment] 2019-03-11 08:00
> I think it is not a bug. It is a feature request.

Actually it's both.

The documentation says that you can specify a range (for example 0-4) for every date/time item of the crontab.
But for weekday the range doesn't work - that's the bug.
So I would suggest to either fix the code or the documentation.

That the weekday format is not not compatible to Linux syntax is a feature request indeed.

**Comment by msinn** [comment] 2019-03-11 18:42
Which documentation do you refer to? I looked at the user documentation of SmartHomeNG and the documentation of smarthome.py. I didn‘t find a description of ranges beeing supported.

**Comment by int-red** [comment] 2019-03-11 20:37
I am referring to this documentation - the user documentation of SmartHomeNG:
https://www.smarthomeng.de/user/konfiguration/items_standard_attribute_crontab.html

> Für jede dieser Zeiteinheiten (Minuten, Stunde, Tag, Wochentag) werden folgende Muster unterstützt (Beispiel jeweils ohne Quotes verwenden):
> 
> eine einzelne Zahl, z.B. „8“ (immer zur/zum 8. Minuten/Stunde/Tag/Wochentag)
> eine Liste von Zahlen, z.B. „0,8,16“ (immer zur/zum 0., 8. und 16. Minute/Stunde/Tag/Wochentag)
> eine Wertebereich, z.B. „0-8“ (immer zwischen dem/der 0. und 8. Minute/Stunde/Tag/Wochentag)
>

**Comment by int-red** [comment] 2019-03-12 11:33
Sorry, closed this by accident - now it's open again

**Comment by bmxp** [comment] 2019-03-12 12:05
I can have a look at it but it will likely not make it into 1.6 ...

**Comment by int-red** [comment] 2019-03-12 12:25
It's not that I'm saying it is necessary to support ranges for weekday.
Just that the documentation says it works with ranges but in fact doesn't.

So how about fixing the documentation instead?

**Comment by bmxp** [comment] 2019-03-16 18:51
I have made some rework which will need thorough testing. It enables the ranges for days as well as it implements months. 
But there is a thing one might want to consider as breaking change.
In documentation it is stated that if for both parameters ``day`` and ``weekday`` something is given instead of ``*`` then the days will add up. This imposes a problem if one wants e.g. to switch on the lights on e.g. only if the 29th of February will be a Saturday.

``11 11 29 2 *`` will currently consider any 29th of February, regardless if it is a saturday.
``11 11 29 2 5* will thus consider any saturday in February and additionally the 29th as well.

I would suggest to make this an ``and`` junction and not an ``or`` one. How does everybody think of it?

**Comment by int-red** [comment] 2019-03-17 08:07
There is a very good discussion about this topic on stackoverflow:
[Why crontab uses OR when both day of month and day of week specified?](https://stackoverflow.com/questions/34357126/why-crontab-uses-or-when-both-day-of-month-and-day-of-week-specified)
Provides lot's of background and in detail information - was interesting to read.

I can see that using an `and` logic instead of the `or` one would offer new use cases like run on "every Friday 13th" or "any 29th of February if it also an Saturday".

But I am a fan of "since it is called crontab it should work like crontab" - which doesn't mean I 
totally against changing the behaviour, but would breaking the standard behaviour of `or` offer so much more convenience?

About the implementation your are working on, maybe using an existing implementation like this one
[https://pypi.org/project/cronex/](https://pypi.org/project/cronex/)
will save you some time. Then you won't have to reinvent the wheel :)
It also offers the interesting # extension which would allow convenient things like "run every 3rd Monday of a month" which is not possible so far.

There is another Python implementation
[https://pypi.org/project/crontab/](https://pypi.org/project/crontab/) 
but it doesn't offer the # extension.

**Comment by bmxp** [comment] 2019-03-17 11:46
Well, I think the creator of smarthome.py did not find a better name than crontab. He might have it named timetriggertab or so but he did not. And he did not implement classic crontab, omitting month, year or other extensions as well as his days are indexed Python way and not linux way.

I do not want to copy crontab from linux but fix the range bug and extend it to present the month.
For the current code, I implemented an optional switch that turns ``and`` junction on while having ``or`` as default. So there is no breaking change by now and I intend to stay compatible as far as possible. We had some compatability issues elsewhere in SHNG and created additional attribute extensions. 

The proposed cronex lib will return for a date and time given if the crontab triggers.
SmartHomeNG's scheduler however needs the time and date to be calculated of the next occurence and it does not check all schedulers every minute.

**Comment by int-red** [comment] 2019-03-17 12:16
> SmartHomeNG's scheduler however needs the time and date to be calculated of the next occurence

The second Python implementation I mentioned
[https://pypi.org/project/crontab/](https://pypi.org/project/crontab/)
does provide this functionality - in it's description it says:  

> it calculates a delay in seconds from when the .next() method is called to when the item should next be executed.

Since the how days are indexed Python way and linux way only is a shift by 1 converting from one to the other is quite simple. You could still use this library internally to help with your implementation and the user would still use the old compatible Python days (0-6)

**Comment by bmxp** [comment] 2019-12-21 06:09
The original described **bug with ranges in days** not supported but documented should be fixed with 2a51e42fe0ffd0028f999807741fb49e02daf4c4

**Closed by bmxp** 2019-12-21 06:09 UTC
Labels: core
