### ISSUE TITLE
Manual not working: "six" error at first start

### ISSUE THREAD

**Issue by maddinador** [smarthomeNG/smarthome#295] opened 2018-10-18 20:03 UTC
Hello,
I've followed the german manual ([Komplettanleitung](https://www.smarthomeng.de/user/installation/komplettanleitung.html)) until the first time smarthomeNG is being started (`python3 ./smarthome.py -v`).
Hardware is RasPi 3B+.
I've executed the requirements-update-script as demanded in the manual.
I've not touched any of the configuration files - they have been created with default settings.
After the start of `smarthome.py` I've opened `<IP>:8383` and nothing shows up.
The console shows:
```
[18/Oct/2018:21:49:51] ENGINE AttributeError("module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1219, in communicate
    req.parse_request()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 689, in parse_request
    success = self.read_request_line()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 889, in read_request_line
    for x in QUOTED_SLASH_REGEX.split(path)
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 889, in <listcomp>
    for x in QUOTED_SLASH_REGEX.split(path)
AttributeError: module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'
```
Is that a known problem? (I think the manual uses the default branch `master` and not `develop`)

I've tried a reinstall of all requirements using `sudo pip3 install --upgrade --force-reinstall -r requirements/base.txt` (six-1.11.0 and cherrypi-18.0.1 are re-installed)
Afterwards the error is gone.

**Comment by bmxp** [comment] 2018-10-19 03:46
The problem is buried within the requirements of CherryPy:

Up to CherryPy 17.4.0 Python versions 2.7 and up and Python 3.4 and up were supported.
Starting with CherryPy 18.0 Python 3.5 is needed, support for Python 2.x was dropped.

So CherryPy 18.0 needs ``cheroot>=6.2.4`` which itself needs  ``six>=1.11.0``. These installation dependencies should be handled by pip, the scope of SmartHomeNG can't cope with it.

As soon as we release a SmartHomeNG 1.6 we will drop officially python 3.4 compatability. This implies that every new installation will then demand Python 3.5 and this will raise the requirements so that ``cherrypy>=18.0`` is needed.

I would suggest to close this issue latest at release of SHNG 1.6.

**Comment by maddinador** [comment] 2018-10-19 09:19
Thanks for the details! 
It sounds like the best solution is to "wait" until `shng-1.6`!? 
When will it be released? (days, weeks or months?)
Update a piece of doc until then?

Is there something I can do to help you guys towards this 1.6 goal?

**Comment by bmxp** [comment] 2018-10-19 15:19
The doc will be updated together with the next master release. This might be end of 2018 or early 2019. In the meantime the will only be hotfixes for master as seen e.g. with 1.5.1.

It depends on how deep you are into Python and SHNG....
The wishlist can be found in the wiki. There is a document about the already finished steps.

**Comment by msinn** [comment] 2018-11-15 08:07
@maddinador 
> It sounds like the best solution is to "wait" until shng-1.6!?

You can go with shNG v1.5.1. Just make sure that you use a recent Python Version. You should use Python 3.5 or Python 3.6 but not Python 3.7.

Compatibility with Python 3.7 is to come with shNG v1.6.

**Closed** 2019-03-29 07:36 UTC
